---
- name: install-debs - create debs cache
  file:
    state: directory
    path: '{{ install_debs_cache_dir }}'

- name: '{{ item | basename }} - copy'
  copy:
    src: '{{ item }}'
    dest: '{{ install_debs_cache_dir }}/'
  with_items: '{{ install_debs }}'

- name: '{{ item | basename }} - install'
  become: true
  apt:
    state: present
    deb: '{{ install_debs_cache_dir }}/{{ item | basename }}'
  with_items: '{{ install_debs }}'
